### ISSUE TITLE
Add notes for things which are deliberately not specified

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#126]
#29 and #96 are not specified, but also don't need to be specified.
Rather than leave an ambiguity of "Was this considered?", add notes to clarify that the behavior is undefined.

Perhaps also mention what common behavior is, if it exists.

**Comment by ProgramMax** [comment]
This was discussed in the [Feb 21st, 2022 meeting](https://lists.w3.org/Archives/Public/public-png/2022Feb/0003.html).

It seems like there are no known problematic images other than ones deliberately crafted to demonstrate the conflicting implementations. So if we specify it (which isn't free), we gain nothing.

I'm happy to hear other thoughts. Maybe we gain something by preventing problematic images being produced in the future. I don't have a good way to gauge that impact.

I definitely think we should at least add a note in both cases though.

**Comment by randy408** [comment]
For https://github.com/w3c/PNG-spec/issues/29 PNG's were crafted to demonstrate the issue, but it all stemmed from a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=428045) concerning an image on wikipedia and Firefox still handles that edge case differently from everything else.
I don't know how prevalent that issue is today, but I wouldn't be surprised if it's still a thing, even today encoders are still far from perfect. Before the default behavior was changed for [spng](https://github.com/randy408/libspng) to ignore invalid standard chunks a user reported a lot of errors that shouldn't exist, one of the most common one was invalid length `bKGD` chunks, these were all user-submitted images. That chunk's length changes based on color type so I assume some popular encoder is still not following spec.

For https://github.com/w3c/PNG-spec/issues/96 I don't have concrete examples though it can lead to some head-scratching when conformance tests are done against the reference implementation with semi-valid PNG's, it is the default behavior after all.

**Comment by svgeesus** [comment]
So, subsequent to the discussion in this issue, #29 was closed by improved wording and backed up by a WPT so it is no longer "deliberately not specified".

Also #96 was at least improved, if not fixed: a common error recovery technque was documented for decoders, and encoders were warned about the variation in recovery and not to rely on a particular method.

Are there other "deliberately not specified" items which should be noted? Otherwise, this issue can be closed.

**Comment by ProgramMax** [comment]
I feel like there were other items. But I can't recall them off the top of my mind.
I will likely be busy through the weekend (I have a friend visiting from overseas), but I will investigate Monday.

**Comment by annevk** [comment]
Why don't we try to define behavior for decoders for all possible inputs? The PR for #96 seems somewhat surprising. Normally we try pretty hard to avoid implementation-defined behavior in the platform.

Also, perhaps that ought to reference https://infra.spec.whatwg.org/#implementation-defined if we truly want it to be implementation-defined?

**Comment by ProgramMax** [comment]
I think the intent of #96 was to be as explicit as possible while noting that there are already decoders with diverging behavior.
I believe we would have preferred non-diverging behavior, but an older spec wasn't clear enough and lead to multiple interpretations.

Am I understanding you correctly? (IE we don't *want* implementation-defined behavior, but it is too late.)

**Comment by annevk** [comment]
We can't ask decoders to change? Perhaps we could at least require decoders used by web browsers to not have implementation-defined behavior?

Regardless, I think we should at least clearly identify implementation-defined behavior by linking the term from Infra.

**Comment by ProgramMax** [comment]
Oh sorry. I thought I had responded this this.
We can ask decoders to change, of course. I already notified the Firefox team that we have now clarified how a decoder should handle a previously ambiguous scenario and they should update.

Also, I agree with what you were saying in general. I previously was narrowly focused on just the implementation-defined behavior which we closed. But there are other parts which we deliberately left unspecified. That should use the official term.

**Comment by ProgramMax** [comment]
I revisited this to see what work can be done so we can close the issue.
I originally said we could add more wording. I *think* the wording I intended to add actually was already added and I missed it. I also don't remember what other things we left intentionally undefined. I no longer know a good reason from my original mindset to keep this open.

But we have since migrated the conversation to adding a reference to "implementation-defined".
@svgeesus, would you be comfortable adding that reference and mentioning it in the places updated in #96?

**Comment by ProgramMax** [comment]
Or @annevk would you be interested in adding the "implementation-defined" reference?

**Comment by svgeesus** [comment]
I think we can do better than that, and [said so](https://github.com/w3c/PNG-spec/issues/96#issuecomment-1630849503) because we have interop on opaque black across the three major browser engines.

**Comment by svgeesus** [comment]
Closed by https://github.com/w3c/PNG-spec/commit/e7f2c51fa8f329cd298771dc55aeb2ad65d9052c which mandates current, interoperable error recovery and avoids any need to say implementation defined.
