### ISSUE TITLE
References section is gone!

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#160]
Not sure when or how it happened, but while preparing to make  a spec edit I noticed we no longer have the [autogenerated References section](https://respec.org/docs/#references-0)

![image](https://user-images.githubusercontent.com/2506926/183880298-c309a87c-667e-4210-b006-c2a9abb37f0a.png)

There are three ReSpec errors, I don't know if they are related though.

**Comment by ProgramMax** [comment]
The last commit where this worked correctly is https://github.com/w3c/PNG-spec/commit/e964b5da354195253276ea1f797d2138d8d5959b

The very next commit broke the side nav bar being generated: https://github.com/w3c/PNG-spec/commit/d6d213b63c7b485ece054625dc16290cc56539ab
It broke because of a missing "," trailing an array element.

This was fixed in https://github.com/w3c/PNG-spec/commit/5fcf7be7be2c3f03d96db7c38274900db8e4c2b8
However, the commit before it accidentally added another missing "," so the effect of the fix wasn't felt.

THAT fix came in https://github.com/w3c/PNG-spec/commit/3a976160bad0eb0a6e083ab331b0308c825a6db7
But by the time the side bar had been restored, the autogenerated reference section was no longer showing up. So the true cause of the break is hidden.

Luckily, there are only 5 hidden changes to investigate. I bisected and manually put the ","s back to restore the side bar.

This bisect gave me the last known good commit being https://github.com/w3c/PNG-spec/commit/6af4e3929723589349fd9887decb8168b3a0f777
And the TRUE offending commit is https://github.com/w3c/PNG-spec/commit/5fcf7be7be2c3f03d96db7c38274900db8e4c2b8

This is where the recently fixed "[??Kasson]]" was introduced. However, fixing it there does not restore the reference section. If I comment out both the "[[?Kasson]]" and "[[?Hill]]" it works. It's only when either (or both) are included that the reference section is no longer generated.

From there, if I delete the "authors" line of Kasson I can uncomment it and still have the references generated. Looking at other biblio entries, I see "author" (singular). So that's one fix.

For Hill, it's the exact same thing.

**Comment by svgeesus** [comment]
Nice sleuthing.

So it turns out that both `author` and `authors` exist. `author` takes a string; `authors` takes an array of strings. Also, using `author` results in the author not being displayed (but no error, and the references section does get generated). Using `authors` with `["J. Bloggs", "J. Doe"]` works correctly and displays both authors. The array can have a single entry.

My pull request not only restores the references section but also restores the missing author name(s)

**Comment by ProgramMax** [comment]
Correct. Thank you for the pull request.

Adding some info here for those who didn't see over in the ReSpec issue: it turns out `author` isn't processed at all. That's why it wasn't causing errors and wasn't showing up. Using `authors` is definitely the correct path forward.
