### ISSUE TITLE
Security considerations: Malware in `eXIf`

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#169]
The [Security Considerations](https://w3c.github.io/PNG-spec/#13Security-considerations) section should mention the possibility of embedding malware inside fields of the EXIF data. For example, [embedding PHP code inside an EXIF Copyright field](https://blog.reversinglabs.com/blog/malware-in-images) has been reported, which might be used to attack certain PHP-based content management systems for example.

**Comment by DavidBuchanan314** [comment]
It's possible to embed data in any section of a PNG, even within the IDAT chunks, or even the pixel values themselves.

It's also possible to create a fully valid PNG/ZIP polyglot file, which is simultaneously considered valid by a strictly conforming PNG parser, and a strictly conforming ZIP parser. The same is true for various other file formats.

I think it would be a fool's errand to try to enumerate all possible ways in which data could be embedded within a PNG file, malicious or otherwise. Anyone trying to security-harden a system by covering all the scenarios listed in a Security Considerations section may be given a false sense of security.

**Comment by randy408** [comment]
Color profiles also have their own file format and may be parsed by a separate library.

**Comment by svgeesus** [comment]
> I think it would be a fool's errand to try to enumerate all possible ways in which data could be embedded within a PNG file, malicious or otherwise. 

I agree that a balance needs to be struck; trying to point out some security issues which have been reported while not attempting to list all possible exploits.

**Comment by svgeesus** [comment]
It sounds as if this is a generic issue with any binary format; data may be embedded somewhere which is then interpreted a different way as one part of a multi-pronged attack. This is hardly unique to PNG, so doesn't really need to be pointed out.

Close?

**Comment by ProgramMax** [comment]
I agree to close.
Data which doesn't fit the file format is a default truth, in my mind. Decoders can choose to handle this however they want.

The PHP example above is reminiscent of SQL injection. Just replace the database with a PNG and SQL with PHP.
I do see value in at least mentioning the possibility as a reminder to people.
To me, SQL injection is well known and understood. So when people accept user input to store via SQL, their minds are likely-enough to consider SQL injection. I'm not sure if the same is true of general file format parsing.

But even if we mention it, we're only reminding people to consider it. And even then, only the people who read that specific section of the spec.
Making people aware-enough of SQL injection came through news stories and tutorials, I think. Not the SQL spec.
So I'm not sure how valuable it would be for us to include the reminder.
