### ISSUE TITLE
Security considerations: malicious data after `IEND`

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#170]
As part of a more complex exploit, [malware looked for encrypted data after `IEND` in a specific image file](https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/rats-wrapped-and-hidden-in-png/). The image file by itself was harmless, it was just used to look less suspicious than a .dll file (which is what the malware decrypted the data to).

Related to

 - https://github.com/w3c/PNG-spec/issues/158

**Comment by ProgramMax** [comment]
I am not a security expert. I defer to others who are.
But I'm not sure there is a lot that can be done about this.

We could suggest that any data before IHDR or after IEND is an illegal image and should not be viewable/valid. But in the case of this virus, the image didn't need to be viewable anyway. It could have just as easily been a .txt file.

Perhaps PNG is relevant here because whatever anti-virus saw the .png and thought things were fine. But it seems like in that case, a .txt could similarly throw it. That would be a bad AV approach.

In either case, hiding data in the file could also happen in iTXt chunks or the likes.

**Comment by svgeesus** [comment]
Yes, we can't prevent this, we can only point it out.

The flaw is in security scanners which consider certain file types as entirely benign.

**Comment by svgeesus** [comment]
The specification [does already say](https://w3c.github.io/PNG-spec/#15FileConformance):

> No chunks or other content follow the [IEND](https://w3c.github.io/PNG-spec/#11IEND) chunk.

**Comment by randy408** [comment]
This new vulnerability is limited to Pixel phones and is caused by bad API design, but it might be worth noting that partial image data is recoverable, even if the beginning of the data stream is missing:
https://www.da.vidbuchanan.co.uk/blog/exploiting-acropalypse.html

**Comment by DavidBuchanan314** [comment]
^ Adding to this: The "street spec" is apparently that most PNG parsers will silently ignore data after IEND.

This is not ideal, because it allows bugs like the above to go unnoticed. Ideally, the spec would mandate that parsers reject images with data after IEND as invalid, but it's too late for that now. Or is it?

Other than images emitted by vulnerable versions of Markup, what percentage of in-the-wild PNGs have trailing data? I suspect that there are very few non-malicious usecases for such files, and as such, PNG parsers could start rejecting images with trailing data without breaking anything important.

Is it worth the potential breakage? To be honest, probably not, but maybe worth thinking about at least.

**Comment by ProgramMax** [comment]
I agree that an unnoticed bug is harder to catch. And I agree that it is at least worth thinking about. We can talk about it in one of our meetings.

I recall a situation where jpegs and PDFs were overlapped. The file was transmitted as a .jpeg which looked like the cover of a book. If you renamed the file to .pdf, you could then read the book. Not that supporting such a weird case is our goal. Just that I've seen this technique used in the wild (for better or worse).

Imagine browser packets coming in and an image showing up. Then suddenly the image disappears because we decide late that the whole thing should be invalid. (Plus, this would require decoders to decide they want this behavior.)

If the spec already has wording around this, there might not be anything for us to change.
It sounds like a scenario where decoders prefer leniency in what they accept. So this should rest on the encoders, perhaps. But we might not be able to suggest changes to codecs. This example problem was in the code which called into the codec. The codec itself couldn't have known.

I suppose it is worth at least pointing out in the security considerations that there is a known problem case.

**Comment by DavidBuchanan314** [comment]
> Imagine browser packets coming in and an image showing up. Then suddenly the image disappears because we decide late that the whole thing should be invalid.

There are already behaviors like this, fwiw. If the final adler32 and/or crc32 is incorrect, the image will un-load the moment the checksum is received (iirc both Chromium and Firefox act like this)

**Comment by ProgramMax** [comment]
Good point

**Comment by ProgramMax** [comment]
TweakPNG alerts the user if there is data past the end of the IEND chunk. So there are apps out there which could have helped.

We talked about acropalypse in our March 20th, 2023 meeting.
We decided that we should certainly add a note in the security considerations section of the possibility of data existing past the end of the IEND chunk. But a viewer app should not be expected to change its behavior for one bug in one creator app.

(That said, I just found that Microsoft's Snipping Tool has the same problem. It doesn't truncate the file to the new size. So that makes two creator apps.) :D

**Comment by svgeesus** [comment]
> Other than images emitted by vulnerable versions of Markup, what percentage of in-the-wild PNGs have trailing data? I suspect that there are very few non-malicious usecases for such files, and so, PNG parsers could start rejecting images with trailing data without breaking anything important.

It is not so much that there are _non-mailicious uses_ for such data, more that some image generating applications _don't bother to trim away_ such data, which has not caused such images to not display so far; the data is just ignored. I would not want to suddenly make images which have displayed correctly fail to display, because of this. That isn't Web compatible.

Instead I would put a warning for encoders. There is already a requirement for decoders not to use such data, and already a privacy note for decoders about potential privacy leak from recovering not-visible data (in various places, including past `IEND`).

**Comment by ProgramMax** [comment]
This still needs added to the security considerations section.
Would anybody be interesting in writing a short sentence (or a few) describing that it is possible for data to exist past the IEND chunk?
