### ISSUE TITLE
We need a definition of 'frame'

### ISSUE THREAD

**Issue by ProgramMax** [w3c/PNG-spec#286]
A definition of 'frame' should probably be in [https://w3c.github.io/PNG-spec/#apng-frame-based-animation](https://w3c.github.io/PNG-spec/#apng-frame-based-animation).

This came up in https://github.com/w3c/PNG-spec/pull/284 where `<!-- need a definition of frame -->` was added to the doc.

**Comment by svgeesus** [comment]
Agree, we do. The description needs to be somewhat nuanced because we need to have a definition that covers:

1. A static PNG
2. An animated PNG where the static image is the first frame
3. An animated PNG where the static image does not form part of the frame-based sequence

We do have some wording [in `cLLi`](https://w3c.github.io/PNG-spec/#cLLi-chunk) about this:

> For static PNG, the [static image](https://w3c.github.io/PNG-spec/#dfn-static-image) is analyzed and is considered to be the first (and only) frame. For animated PNG, each frame of the[ frame-based animation](https://w3c.github.io/PNG-spec/#apng-frame-based-animation) sequence is analyzed.

If we have a definition of frame, that could be simplified to

> Each `<a>`frame`</a>` is analyzed.

**Comment by svgeesus** [comment]
Would be fixed by PR https://github.com/w3c/PNG-spec/pull/305
