### ISSUE TITLE
Terminology - SDR, HDR, PQ, HLG

### ISSUE THREAD

**Issue by simontWork** [w3c/PNG-spec#343]
These terms are used in the document without definition.

The final 2 are easily defined by reference to the relevant ITU specification.

However, SDR seems to be being used interchangeably with BT.709, whilst the term encompasses a larger range of RGB image formats including sRGB, Adobe RGB 1998, ROMM RGB (ProPhoto), BT.601, BT.2020 etc.

Similarly, HDR encompasses HLG and PQ and other proprietary and standard image and video formats.

**Comment by svgeesus** [comment]
Overall these suggestions are an improvement.

However due to a trademark issue that has tripped us up before in terms of implied endorsement etc, I sadly must object to the use of the term Adobe RGB (or Adobe 1998 RGB, etc) and suggest instead Display P3.

**Comment by simontWork** [comment]
Works for me, it's an inexhaustive list so can drop Adobe and replace with Display P3 (Do we need to define white point as there are two variants).  It's not a direct replacement as I believe the primaries are slightly different.  Perhaps add "Other SDR formats can be represented by ICC Profiles and can therefore be present in PNG"?

**Comment by svgeesus** [comment]
> replace with Display P3 (Do we need to define white point as there are two variants

No, DCI P3 has two variants with differing white points. Display P3 uses D65.

**Comment by digitaltvguy** [comment]
I'd like to make a few suggestions to the text:

Hybrld Log-Gamma (HLG) - defined in ITU-R BT.2100 Table 5. (A relative scene-referred system)
Perceptual Quantiser (PQ) - defined in ITU-R BT.2100 Table 4. NB only RGB may be used in PNG (An absolute display-referred system)
Standard Dynamic Range (SDR) - an image format capable of storing images with a relatively low range of detail in light intensities (~ 6-8 stops). Examples include sRGB, Adobe RGB, ITU-R BT.709 (transfer function). SDR should not be confused with a term that describes color spaces because SDR can be used with different color spaces like BT.2020, P3, etc..

High Dynamic Range (HDR) - A method of representing a greater range of detail to describe light intensities similar to or in excess of the human visual system's instantaneous dynamic range (~12-14 stops). PNG allows the use of 2 HDR formats, HLG and PQ which can store approximately 15 or 20 stops.

A "Stop" defines a change in scene light luminance using a factor of 2.

**Comment by svgeesus** [comment]
Closed by https://github.com/w3c/PNG-spec/commit/46c5343e30a81034b2defe22cb25f6a4027a4f72
