### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by ace-dent** [w3c/PNG-spec#370]
I have worked informally around the `png` format for ~20 years.
In this new Spec work, there clearly has been much effort to expand the capabilities of the format, esp. in the areas of color fidelity.
My concern is _Why_? I write this not to antagonise... but truly understand the motivations...

I am certainly a dedicated 'fan' of the format but also accept it's limitations. 
There are fundamental, inherent flaws in compression (interleaved RGBA bytes, choice of encoding algorithms, excessive checksums, etc.), that are vestigials from the time it was created. 

We are now presented with **lossless** JPEG XL (JXL), based on contemporary compression methods and developed to support the latest needs for storing extended color- and meta- data. I firmly expect this technology to become the de facto standard for the coming decades.

So _Why_ are we working to extend png, to duplicate these features? Beyond the human labour involved, we are adding a legacy of decoding software necessary to support these features. This adds overhead to all browsers for many, many years... 

I understand the effort to standardise the 'hacked' features that emerged (exif, APNG, etc.).
I just cannot imagine anyone trying to add HDR to the GIF format at this stage...

I look forward to being illuminated,
Many thanks, 
Andrew 

Update: The technical aspects are addressed [here](https://github.com/w3c/PNG-spec/blob/main/Third_Edition_Explainer.md), but lacks an analysis of competing formats that already support the requirements.

**Comment by ProgramMax** [comment]
Hello.
I love JPEG XL. I don't see us as competing image standards, so much as brothers trying to support each other's growth. I think they feel the same. It isn't a pie, where a bigger slice for them means a smaller slice for us. That said, JXL has a set or cons to go with its pros. I'm going to point them out in order to answer your question. But know that I'm not attacking JXL -- I love it.

JXL is a significantly more complicated format from a hardware decoder's point of view. This has been a major issue for JXL on gaining traction. As much as we all love JXL, that doesn't mean hardware vendors do. They have pushed back because of this complication. This is important for things like TVs, the whole video production pipeline (and testing)...
And even when hardware isn't a limitation, the complication still matters. For example, embedded devices can be slower or use more power to decode. Now TV manufacturers need a more powerful (and expensive) chip. So when you said you expect this to become the de facto standard, if you meant JXL's compression methods (rather than HDR) then the industry hardware folks would disagree with you. (VP9 faces the same issues from the same group.)

You mentioned the human labor involved, overhead for browsers...
Chromium-based browsers *already* support the bulk of PNG Third Edition. The overhead and work was much lower than adding JXL. (Side note: I do want JXL support in browsers. Again, we aren't competing.) IMHO, these updates are the lowest effort, highest value path towards HDR support for users.

But to answer the bigger picture "Why update PNG at all?": PNG as a format shouldn't become outdated / obsolete. For example, each frame of a gif is limited to 256 colors. That limitation is a problem for modern images. It provides people a compelling reason *not* to use the format. This isn't good for users.

PNG Second Edition has hard limitations (HDR, animation). Softer limitations like the excessive checksums you mentioned can sometimes be ignored. But these hard limitations are a show-stopper. And that puts PNG Second Edition in danger of becoming outdated.

Any human labor involved is because there is a real need for it, with users asking for it. It isn't needlessly forced extra work. It is helping people solve the problem they have.

If you accept the idea of not becoming outdated, you might also accept extrapolating it with the idea that future PNG specs should actually push the future. Rather than simply prevent PNG's death, we can have PNG be cutting-edge. (Of course, this should be tempered with user demand so we don't waste anyone's time.)

And finally, there shouldn't be only one solution. For example, W3C wants to see multiple independent implementations to confirm viability. Web SQL--a feature I still strongly desire--never became a full standard because all browser vendors used the same SQL implementation. And of course the ideas of single-point-of-failure and bus-factor.

Hopefully, you now feel like PNG definitely should be updated. If not, I'm happy to continue thinking it over with you.

**Comment by richgel999** [comment]
The way I look at the situation:
.QOI was a strong sign that programmers, a whole lot of them, really like simple, understandable, "sane" image file formats. Its spec fits on a single sheet of paper, and an entire .QOI "codec" is a few 100 lines of simple, easy to understand (and easy to secure) code. To .QOI users, even .PNG is too complex/slow.

.EXR: It's telling that TinyEXR -- which is ~10,000 lines of code, not counting Deflate -- can only load around 70% of the wild .EXR images I've tried using for testing in our new texture codec development work. The .EXR format is too complex. The official lib, OpenEXR is too much code (many several dozen source files). _I still don't have a reliable way of reading/writing half-float images, and need to keep looking._ 

I can't drop OpenEXR into my project because my customers would scream. Even TinyEXR is a stretch. No way could I drop in JPEG XL. Its source code would likely bloat the project's size and compile time by a large factor.

The alternative JPEG formats, like JPEG XL: They are just too complex vs. plain JPEG or PNG. Pages and pages of complexity, enormously complicated algorithms, exotic colorspaces, dozens of source code files, just to save or read an image. We're not using modems anymore, so the motivation to shave every last bit from an image file just isn't there like it used to be. I can't drop any of this stuff into my project. The ratio of new value delivered vs. complexity/compile time/development cost/perf isn't there.

Developers already use .PNG, and it already supports 16-bit/component images. All the major .PNG readers in the wild already support 16-bit images. I wrote and tested a full from-scratch .PNG decoder in a couple days of work. The core .PNG spec is very elegant, simple, and understandable. It has withstood the test of time. Adding half float in a backwards compatibility way, if that's possible, is a total no brainer to me and my customers. 

I think adding lossless half-float images to PNG can be done in a way where old (non-half float aware) software still reads/views the image without any fuss. _It's already possible to store half-float images into PNG right now, without modifying a single line of .PNG code anywhere._ We just need an ancillary chunk that communicates "hey this is half-float data, possibly shifted left X bits".

At the end of the day, positive half floats, when interpreted as 16-bit unsigned values, are just a piece-wise linear approximation to the log2 function (Blinn). They're just 16-bit/component pixels for lossless compression purposes.

**Comment by ace-dent** [comment]
Thanks for your considered responses to my question. Really appreciate it.

@ProgramMax 

> I love JPEG XL. I don't see us as competing image standards

To be clear, my first _love_ will alway be png! ...I also see the pros/cons for JXL.

> IMHO, these updates are the lowest effort, highest value path towards HDR support for users.

Understood and agreed. Thank you for your clear explanation.

> If you accept the idea of not becoming outdated, you might also accept extrapolating it with the idea that future PNG specs should actually push the space.

Yes... provided all additions support backwards compatibility (obviously!)... and consider graceful degradation for simpler decoders. (i.e. I'd always want a reasonable approximation of an image even with a [minimal decoder](https://github.com/KolibriOS/kolibrios/blob/b9d43b416f9cca2a8c8525eb502508b5dfe1deaf/programs/develop/libraries/libs-dev/libimg/png/png.asm)).

<hr>

@richgel999 

> To .QOI users, even .PNG is too complex/slow.

Yes. An interesting and thought-provoking development.

> ... the motivation to shave every last bit from an image file just isn't there like it used to be.

Perhaps I still live in that dial-up-modem era! 😅  ...

> Adding half float in a backwards compatibility way, if that's possible, is a total no brainer to me and my customers.

Hmm. I do worry about use-cases that support specific businesses. The vendor-isation of the Standard by Apple, etc. has been detrimental and a wasted opportunity IMHO. I'm grateful to the standardisation effort here, to consider the needs of *all* stakeholders. 

<hr>

Thanks again for the patient and clear explanation of this work.
I'm certainly not the target audience... I've always seen 16-bits/channel as bourgeois and immediately strip out gamma chunks as 'unsupported' ... 😆 ...but understand the necessary progress to keep png relevant.

Marking as Closed.
