### ISSUE TITLE
eXIf chunk change incompatible with the previously approved specification

### ISSUE THREAD

**Issue by jbowler** [w3c/PNG-spec#447]
The eXIf chunk was approved here:

https://sourceforge.net/p/png-mng/mailman/message/35943428/

The chunk specification is http://www.simplesystems.org/png-group/proposals/eXIf/png-proposed-eXIf-chunk-2017-06-15.html#C.eXIf and it includes the following:

>**The eXIf chunk may appear anywhere between the IHDR and IEND chunks except between IDAT chunks**

The new v3 specification declares that the eXIf chunk (which, note, is still safe-to-copy) must occur before IDAT.  This would apparently invalidate existing valid PNG files.

There is extensive discussion of this in the rationale and on png-mng-misc.

That data isn't going to go away and must not be made invalid.  Once it is valid it remains valid.

**Comment by svgeesus** [comment]
If you look at [5.6 Chunk ordering](https://w3c.github.io/PNG-spec/#5ChunkOrdering) you will notice that most chunks come before `IDAT`. Two (`fcTL` and `fdAT`) necessarily come after `IDAT`. The four that can come anywhere (`tIME`, `iTXt`, `tEXt` and `zTXt`) do not affect image rendering in any way. `eXIf`, because it contains an image orientation, affects image rendering.

To avoid re-layout, browsers ignore any EXIF which occurs after image data.

Thus, best interoperability is achieved by requiring `eXIf` to come before `IDAT`.

The [original proposal]([ttp://www.simplesystems.org/png-group/proposals/eXIf/png-proposed-eXIf-chunk-2017-06-15.html#C.eXIf](http://www.simplesystems.org/png-group/proposals/eXIf/png-proposed-eXIf-chunk-2017-06-15.html#C.eXIf)) states:

> Safe-to-copy ("eXIf") versus unsafe-to-copy ("eXIF"): The Exif profile (and thus the eXIf chunk) may contain not only material that is safe-to-copy, such as camera, lens, exposure and GPS information, but also unsafe-to-copy material about the image data, such as image orientation, width, height, gamma, and JPEG-specific compression information. We resolved that by including a statement that such unsafe-to-copy material should be regarded as historical in nature only, and made the chunk safe-to-copy to reduce the risk of losing valuable information.

That isn't Web compatible; the image orientation **is** respected, and can't be brushed off as _merely historical_ because existing web pages rely on that information..

**Comment by svgeesus** [comment]
The original discussion about that is 

 - https://github.com/w3c/PNG-spec/issues/146

**Comment by ProgramMax** [comment]
libpng added eXIf support in 1.6.3, released on July 18, 2013.

Firefox explicitly ignores the eXIf chunk. [Glenn Randers-Pehrson even patched Firefox in 2017 to add the eXIf chunk to the list of unknown chunks](https://bugzilla.mozilla.org/show_bug.cgi?id=1402140) so a build using the system libpng would ignore it as well.
[That behavior remains today](https://searchfox.org/mozilla-central/source/image/decoders/nsPNGDecoder.cpp#279).


Chromium [only reads eXIf from within PNGImageDecoder::HeaderAvailable](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/image-decoders/png/png_image_decoder.cc;l=489;drc=972faf553dfe71f6d55c9ea2cce4b7d3ef30502b). This function is [called when the first IDAT is encountered](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/image-decoders/png/png_image_reader.cc;l=642;drc=c0265133106c7647e90f9aaa4377d28190b1a6a9) (so enforcing "before IDAT" behavior). But that was [added by me in 2024 to mimic what this spec said](https://chromium-review.googlesource.com/c/chromium/src/+/5249880). Prior to that, the eXIf chunk was just ignored like it is in Firefox.


All this is to say the previous eXIf definition which allowed the eXIf chunk to arrive after IDAT was not being followed on the web. So there are no new breakages there. (I don't have a good way to test old MacOS / Safari.)


[libpng currently checks that eXIf comes after IHDR but doesn't check if it comes before IDAT](https://github.com/pnggroup/libpng/blob/f1848a3b560ddcad065242268433af475948461e/pngrutil.c#L2037). Contrast that to the way [libpng handles bKGD, which is by checking after IHDR and before IDAT](https://github.com/pnggroup/libpng/blob/f1848a3b560ddcad065242268433af475948461e/pngrutil.c#L1919). This means libpng follows the png-mng-misc suggested behavior. EXCEPT libpng also allowings eXIf between IDAT chunks, which is explicitly disallowed by png-mng-misc. So libpng only half-follows the png-mng-misc suggested behavior.


That said, [any png eXIf written with libpng is done inside png_write_info()](https://github.com/pnggroup/libpng/blob/f1848a3b560ddcad065242268433af475948461e/pngwrite.c#L243), which puts it [before all IDAT chunks](https://github.com/pnggroup/libpng/blob/f1848a3b560ddcad065242268433af475948461e/contrib/gregbook/writepng.c#L225).

We would need to find an encoder which 1.) knows about eXIf, and 2.) places it after all IDATs to identify a problem. I'm struggling to find one.
Photoshop does not know about the eXIf chunk.
GIMP does (heyyy good job, GIMP!). But only when loading. Once loaded, it applies the rotation and discards the EXIF information. That means when the image is later saved, the eXIf chunk is gone. So this doesn't satisfy the "encoder which __".

Can you help me find where in the png-mng mailing lists it was reasoned that eXIf should be allowed after IDAT? I can't find it. If I had to guess, it would be because of the displayed vs. not-displayed behavior (similar to the safe-to-copy vs. not-safe-to-copy). Camera and lens information can come after IDAT with no problems. In fact, it probably should so the image can be displayed sooner while downloaded. However, the rotation information of EXIF is problematic if it comes after IDAT, as found in the discussions @svgeesus linked above.

If my guess about png-mng's reasoning is right & given there is no new web breakage & I need to hunt pretty hard to find a case where this problem actually happens (I haven't found any cases), I feel confident saying the benefits of the "before IDAT" behavior are worth it.

**Comment by ProgramMax** [comment]
I'm going to close this issue because I believe the current spec wording is correct.
Feel free to comment and re-open if we find an encoder that saves eXIf after all IDATs.
